### PR TITLE
Create docker file and docker build push CI

### PR DESCRIPTION
**Pull request by henryclw**
### Why docker?

Make it easier to deploy and debug. Since everyone can pull the same image from Docker Hub and the npm dependencies would be handled well in the building stage of docker image. Also this makes it easier to deploy for the machines that have docker but no node.js environment.

### Discussion

What is the purpose of setting `SESSION_SECRET=abc123`, should this be different for every deployment? If so, maybe we should set this SESSION_SECRET through a environment variable in docker?

### TODO before merge

- [ ] Create Docker Hub account for this organization
- [ ] Fill in the GitHub action secretes
- [ ] Create the Docker Hub repo named `jsonhero-web` or anything you like
- [ ] Update the repo names in README.md <https://github.com/henryclw/jsonhero-web/blob/1ec0a38a4f2aa22d659258c383119aa035ffb15c/README.md?plain=1#L144>

### TODO after merge

- [ ] Check the actions, are they working as expected
- [ ] Check your Docker Hub account, are the newly pushed images as expected
- [ ] Pull one of the image and try to run it locally

Any suggestions are welcomed!

### CODE REVIEW

**Comment by ericallam** [comment]
Hey @henryclw, thanks for the PR! I will have some time tomorrow to review and give feedback 👍

**Comment by mhdfv** [comment]
I just pulled the Docker image [henryclw/jsonhero-web](https://hub.docker.com/r/henryclw/jsonhero-web) which I guess is the same image that's built here.

The server starts up just fine but whenever I put in a JSON I get the following errors:

### Web
```
Error: Unexpected Server Error
    at handleDataRequest (/app/node_modules/@remix-run/server-runtime/esm/server.js:163:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at requestHandler (/app/node_modules/@remix-run/server-runtime/esm/server.js:41:20)
    at handleEvent (/app/node_modules/@remix-run/cloudflare-workers/esm/worker.js:98:18)
    at EventTarget.[kDispatchFetch] (/app/node_modules/@miniflare/core/src/standards/event.ts:359:13)
    at Server.<anonymous> (/app/node_modules/@miniflare/http-server/src/index.ts:168:20)
```

### Container Logs
```
jsonhero               | [1] GET /actions/createFromFile?_data=root 200 OK (183.00ms)
jsonhero               | [1] TypeError: Value of "this" must be of type Crypto
jsonhero               | [1]     at new NodeError (node:internal/errors:372:5)
jsonhero               | [1]     at getRandomValues (node:internal/crypto/webcrypto:702:11)
jsonhero               | [1]     at Proxy.<anonymous> (/app/node_modules/@miniflare/core/src/standards/helpers.ts:35:16)
jsonhero               | [1]     at /app/app/jsonDoc.server.ts:102:14
jsonhero               | [1]     at /app/node_modules/nanoid/index.js:26:19
jsonhero               | [1]     at createId (/app/app/jsonDoc.server.ts:106:10)
jsonhero               | [1]     at createFromRawJson (/app/app/jsonDoc.server.ts:60:17)
jsonhero               | [1]     at createFromUrlOrRawJson (/app/app/jsonDoc.server.ts:34:12)
jsonhero               | [1]     at action2 (/app/build/route:/app/app/routes/actions/createFromUrl.ts:26:21)
jsonhero               | [1]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
jsonhero               | [1]   code: 'ERR_INVALID_THIS'
jsonhero               | [1] }
jsonhero               | [1] POST /actions/createFromUrl?_data=routes%2Factions%2FcreateFromUrl 500 Internal Server Error (1322.03ms)
```

Maybe SESSION_SECRET  related?

**Comment by ericallam** [comment]
On review I don't think that running this in Docker makes that much sense, since it is meant to be deployed to Cloudflare Workers (which powers jsonhero.io). Cloudflare Workers is not a Node.js environment. I appreciate the enthusiasm with which this PR was constructed, and it still might be useful down the line if we ever transition from CF Workers to a Node.js environment, but for now I think I'm going to close it.

**Comment by henryclw** [comment]
> On review I don't think that running this in Docker makes that much sense, since it is meant to be deployed to Cloudflare Workers (which powers jsonhero.io). Cloudflare Workers is not a Node.js environment. I appreciate the enthusiasm with which this PR was constructed, and it still might be useful down the line if we ever transition from CF Workers to a Node.js environment, but for now I think I'm going to close it.

Yes, for the time being you may not need docker to deploy it. But this maybe a good option for other developers who want to deploy their own instance. Say in some offline environment or so. Docker is just a nice way to deploy, one maybe interested in this repo but doesn't have the corresponding environment (say npm) for it. But he/she do has docker installed. Then this could be done easily without any npm environment configuration. 

If there's other developer also want this feature, it's nice if you take more consideration. This feature may attract more people if they can use it easily.

Thank you for your kind reply after all.

**Comment by henryclw** [comment]
> I just pulled the Docker image [henryclw/jsonhero-web](https://hub.docker.com/r/henryclw/jsonhero-web) which I guess is the same image that's built here.
> 
> The server starts up just fine but whenever I put in a JSON I get the following errors:
> 
> ### Web
> ```
> Error: Unexpected Server Error
>     at handleDataRequest (/app/node_modules/@remix-run/server-runtime/esm/server.js:163:31)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at requestHandler (/app/node_modules/@remix-run/server-runtime/esm/server.js:41:20)
>     at handleEvent (/app/node_modules/@remix-run/cloudflare-workers/esm/worker.js:98:18)
>     at EventTarget.[kDispatchFetch] (/app/node_modules/@miniflare/core/src/standards/event.ts:359:13)
>     at Server.<anonymous> (/app/node_modules/@miniflare/http-server/src/index.ts:168:20)
> ```
> 
> ### Container Logs
> ```
> jsonhero               | [1] GET /actions/createFromFile?_data=root 200 OK (183.00ms)
> jsonhero               | [1] TypeError: Value of "this" must be of type Crypto
> jsonhero               | [1]     at new NodeError (node:internal/errors:372:5)
> jsonhero               | [1]     at getRandomValues (node:internal/crypto/webcrypto:702:11)
> jsonhero               | [1]     at Proxy.<anonymous> (/app/node_modules/@miniflare/core/src/standards/helpers.ts:35:16)
> jsonhero               | [1]     at /app/app/jsonDoc.server.ts:102:14
> jsonhero               | [1]     at /app/node_modules/nanoid/index.js:26:19
> jsonhero               | [1]     at createId (/app/app/jsonDoc.server.ts:106:10)
> jsonhero               | [1]     at createFromRawJson (/app/app/jsonDoc.server.ts:60:17)
> jsonhero               | [1]     at createFromUrlOrRawJson (/app/app/jsonDoc.server.ts:34:12)
> jsonhero               | [1]     at action2 (/app/build/route:/app/app/routes/actions/createFromUrl.ts:26:21)
> jsonhero               | [1]     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
> jsonhero               | [1]   code: 'ERR_INVALID_THIS'
> jsonhero               | [1] }
> jsonhero               | [1] POST /actions/createFromUrl?_data=routes%2Factions%2FcreateFromUrl 500 Internal Server Error (1322.03ms)
> ```
> 
> Maybe SESSION_SECRET related?

Thank you for pointing out. I didn't notice this because with my local docker build cache, everything works fine. But if I prune the local build cache and build from the beginning once again, I get the same error. For the time being I have no idea what went wrong.

But I've upload my local successful build as `henryclw/jsonhero-web:latest` with digest `0b3e891687e6c284a1796c5a9d6a9924d45bf3193da60e8990382dac6afa163e` and image id `faffd0f51032`. You could try this one if you don't mind.

**Comment by mhdfv** [comment]
@henryclw Awesome, that new built works out of the box! Thanks!

@ericallam Your argumentation makes sense! But just to give you an example: in my case I can't deploy to Cloudflare or any other cloud service due to data privacy concern of my employee. I just wanted to give our developers a quick way to visualize and debug our internal API responses that may contain customer information. So a quick docker run in our local environment is the fastest and best way to achieve this.

**Pull request closed without merging**
